### ISSUE TITLE
Request: Multi upload

### ISSUE THREAD

**Issue by Phyks** [Schoumi/Goblim#3]
Hi,

Would be really cool if one could do multiple uploads at the same time in the app. Would be cool also to be able to share (or copy) links to multiple images. 

This is something doable in desktop web interface but very hard to do on mobile devices due to limitations in file selection for upload. 

Thanks!

**Comment by Phyks** [comment]
Same thing stands for the "share" widget in other apps (typically gallery). If I select one image, it offers "Goblin" as a sharing method. If I select multiple, it does no longer offer it =(

**Comment by Kratsac** [comment]
That's exactly what I would like to ask for. 👍

**Comment by Schoumi** [comment]
I have move my dev repository to my own gitlab: https://git.mob-dev.fr
You can find issues for Goblim here: https://git.mob-dev.fr/Schoumi/Goblim/issues

I work on this feature in the next few days/week.

This repository will disapear in few weeks. I have activated the authentication through github to my gitlab to help user for the transition if needed.

Thanks

**Comment by Phyks** [comment]
Ok :) Thanks_
